Repository Train0303/PNU-Notification, pull requests merged in 2023-03, with the labels that each got.

#5 Pull request Feature/logging to develop
  .gitignore
  pnuNoti/settings/__init__.py
  pnuNoti/settings/base.py
  pnuNoti/settings/local.py
  pnuNoti/settings/prod.py
  registration/middleware.py
  static/bootstrap.min.css
  static/bootstrap.min.js
  static/registration/check_email.js
  static/style.css
  templates/navbar.html
  templates/registration/login.html
  templates/registration/password_reset_email.html
  templates/registration/password_reset_form.html
  templates/registration/signup.html
Labels: enhancement

#7 Pull request Feature/logging to develop
  .gitignore
  pnuNoti/settings/__init__.py
  pnuNoti/settings/base.py
  pnuNoti/settings/local.py
  pnuNoti/settings/prod.py
  registration/middleware.py
  static/bootstrap.min.css
  static/bootstrap.min.js
  static/registration/check_email.js
  static/style.css
  templates/navbar.html
  templates/registration/login.html
  templates/registration/password_reset_email.html
  templates/registration/password_reset_form.html
  templates/registration/signup.html
Labels: enhancement

#9 Pull request feature/modifyStatic to develop
  .staticfiles/bootstrap.min.css
  .staticfiles/bootstrap.min.js
  .staticfiles/registration/check_email.js
  .staticfiles/style.css
  static/style.css
Labels: enhancement

#10 Pull request feature/UserGuide to develop
  .staticfiles/favicon.ico
  .staticfiles/style.css
  .staticfiles/subscribe/userguide.png
  pnuNoti/urls.py
  static/favicon.ico
  static/style.css
  static/subscribe/userguide.png
  templates/subscribe/create_subscribe.html
Labels: enhancement

#11 feat: implements django-mysql
  Dockerfile
  docker-compose.yml
  pnuNoti/settings/prod.py
  registration/management/__init__.py
  registration/management/commands/initadmin.py
  requirements.txt
Labels: enhancement

#12 Pull request feature/FindPasswordEmailExistsCheck to develop
  pnuNoti/settings/base.py
  registration/middleware.py
  registration/views.py
  templates/registration/password_reset_form.html
Labels: enhancement

#13 feat: modify DATABASES OPTIONS settings
  pnuNoti/settings/prod.py
Labels: enhancement

#14 Pull request feature/AsyncSendMail to develop
  registration/async_send_mail.py
  registration/views.py
  templates/navbar.html
  templates/registration/verification_need.html
  templates/subscribe/create_subscribe.html
Labels: enhancement

#15 Pull Request feature/crontab to develop
  .staticfiles/style.css
  Dockerfile
  config/cron/cron.sh
  config/nginx/nginx.conf
  docker-compose.yml
  notice/management/commands/crontab_mail.py
  notice/models.py
  pnuNoti/settings/base.py
  pnuNoti/settings/local.py
  pnuNoti/settings/prod.py
  static/style.css
Labels: enhancement

#16 refac: crontab refactoring
  Dockerfile
  docker-compose.yml
  pnuNoti/settings/local.py
Labels: enhancement

#17 Pull request feature/DeleteSubscribe to develop
  notice/management/commands/crontab_mail.py
  registration/async_send_mail.py
  registration/views.py
  static/style.css
  static/subscribe/delete_subscribe.js
  subscribe/urls.py
  subscribe/views.py
  templates/registration/password_reset_email.html
  templates/registration/verification_email.html
  templates/subscribe/create_subscribe.html
  templates/subscribe/update_subscribe.html
Labels: enhancement

#21 fix: jQuery CDN http to https
  templates/base.html
Labels: bug

#22 Pull request develop to main
  .staticfiles/style.css
  templates/base.html
Labels: enhancement

#23 pull request develop to main
  pnuNoti/settings/prod.py
Labels: bug

#24 feat: add user withdrawal
  registration/permission.py
  registration/urls.py
  registration/views.py
  static/style.css
  templates/navbar.html
  templates/registration/withdrawal.html
Labels: enhancement

#26 Pull request feature/addRssLinkRule to develop
  pnuNoti/settings/prod.py
  registration/views.py
  static/favicon.ico
  static/index/example1.jpg
  static/index/example2.jpg
  static/index/example3.jpg
  static/style.css
  templates/base.html
  templates/footer.html
  templates/registration/signup.html
  templates/start.html
Labels: enhancement

#27 Pull request feature/FixNavbar to develop
  .staticfiles/javascript.js
  .staticfiles/style.css
  static/javascript.js
  static/style.css
  templates/base.html
Labels: enhancement

#28 Pull request fix/fixHC to develop
  pnuNoti/settings/prod.py
Labels: bug

#29 pull request develop to main
  .staticfiles/favicon.ico
  .staticfiles/index/example1.jpg
  .staticfiles/index/example2.jpg
  .staticfiles/index/example3.jpg
  .staticfiles/javascript.js
  .staticfiles/style.css
  pnuNoti/settings/prod.py
  registration/permission.py
  registration/urls.py
  registration/views.py
  static/favicon.ico
  static/index/example1.jpg
  static/index/example2.jpg
  static/index/example3.jpg
  static/javascript.js
  static/style.css
  templates/base.html
  templates/footer.html
  templates/navbar.html
  templates/registration/signup.html
  templates/registration/withdrawal.html
  templates/start.html
Labels: enhancement

#30 Pull request feature/decorateReadme to develop
  README.md
  assets/structure.png
Labels: documentation

#32 Pull Request fix/fixSendMail to develop
  notice/management/commands/crontab_mail.py
  notice/management/utils.py
  pnuNoti/backends.py
  pnuNoti/settings/base.py
  pnuNoti/settings/local.py
  pnuNoti/settings/prod.py
Labels: documentation, enhancement

#33 Feature/add school noti
  notice/crawl_hakjisi.py
  notice/management/commands/crontab_mail.py
  notice/management/commands/crontab_mail_hakjisi.py
  notice/models.py
  registration/management/commands/init_hakjisi.py
  registration/models.py
  registration/urls.py
  registration/views.py
  static/registration/signup.js
  static/registration/update_active.js
  static/style.css
  subscribe/forms.py
  subscribe/models.py
  subscribe/permission.py
  subscribe/urls.py
  subscribe/views.py
  templates/footer.html
  templates/navbar.html
  templates/registration/index.html
  templates/registration/password_reset_form.html
  templates/registration/signup.html
  templates/registration/verification_need.html
  templates/registration/verification_result.html
  templates/subscribe/create_subscribe.html
  templates/subscribe/update_hakjisi_subscribe.html
  templates/subscribe/update_subscribe.html
Labels: enhancement

#34 feat: fixed navbar appearance
  .staticfiles/javascript.js
  .staticfiles/style.css
  static/javascript.js
  static/style.css
  templates/base.html
  templates/navbar.html
  templates/registration/index.html
Labels: bug, enhancement

#36 modify: modified message of crontab_mail_hakjisi
  notice/management/commands/crontab_mail_hakjisi.py
Labels: enhancement

#38 Feature/modify email message
  notice/management/commands/crontab_mail.py
  notice/management/commands/crontab_mail_hakjisi.py
  templates/base.html
  templates/mail_base.html
  templates/notice/mail_template.html
  templates/registration/password_reset_email.html
  templates/registration/verification_email.html
Labels: enhancement

#39 PR develop to main
  notice/management/commands/crontab_mail.py
  notice/management/commands/crontab_mail_hakjisi.py
  templates/base.html
  templates/mail_base.html
  templates/notice/mail_template.html
  templates/registration/password_reset_email.html
  templates/registration/verification_email.html
Labels: enhancement

#43 Pull request fix/fixCrontabhak to develop
  notice/crawl_hakjisi.py
  notice/management/commands/crontab_mail.py
  pnuNoti/core/__init__.py
  pnuNoti/core/http_session.py
Labels: enhancement

#45 Pull request feature/modifyUI to develop
  .staticfiles/index/example1.jpg
  static/index/example1.jpg
  templates/registration/signup.html
Labels: enhancement

#47 Pull request fix/fixlogIP to develop
  registration/middleware.py
Labels: bug
